# Change the prefix key to C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# break pane into new window #
bind C-c break-pane

# kill server shortcut #
bind Q kill-server

# Some tweaks to the status line
set -g status-right "%H:%M"
set -g window-status-current-style "underscore"

# Change the default $TERM to tmux-256color
set -g default-terminal "screen-256color"


set -g status-style 'bg=#333333 fg=#40E0D0'

bind r source-file ~/.tmux.conf
set -g base-index 1

set -ga terminal-overrides 'urxvt*:smcup@:rmcup@'


### COLOURS ###

# default statusbar colors
set-option -g status-style fg=#00D3FF,bg=#333333

# active window title colors
set-window-option -g window-status-current-style fg=#00D3FF,bg=#000000
#set-window-option -g window-status-current-style bright

# pane border
set-option -g pane-border-style fg=#222222
set-option -g pane-active-border-style fg=#FFFF00
set-option -g pane-border-lines single
set-option -g pane-border-status top
